### PR TITLE
Patched annoying timed message

### PR DESCRIPTION
**Pull request by Lyut**
Patches an annoying message that pops up every 10 minutes or so, saying "Thank you for using our demo version"

### CODE REVIEW

**Comment by StackOverflowExcept1on** [comment]
Hi, I'll check it soon. I remember that this appears once every 30 minutes.

**Comment by StackOverflowExcept1on** [comment]
It doesn't work on my machine

**Comment by Lyut** [comment]
My apologies, it's the first time I use Frida, I must have done something wrong but it seems to work on my machine (Linux 6.3.3-arch1-1 x86_64).

I installed IDA Demo 7.5.200603, followed the xref to "<b>Thank you for using our demo version!</b>" and inverted the jump condition.
scrot_20230612_152820
scrot_20230612_153303

I have ran IDA several times for more than a couple of hours and it seems to work. The pop-up only shows when closing an IDA database, but not every 30 minutes

**Comment by StackOverflowExcept1on** [comment]
image
hmm, I tried to write `0x90 0x90` and `0x75 0x26` to that address, but after 30 minutes the message still appears.

**Comment by Lyut** [comment]
My bad, I was testing multiple patches and forgot to add a chunk of NOPs. Try if it works with this and I'll commit an update:
`patch(ida64.add(0x27E2FB), [0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90])`

The popup when closing a project/exiting IDA should be gone aswell.
Thank you for this project and your time!

**Comment by StackOverflowExcept1on** [comment]
Looks good. I will check and merge if everything is ok. After applying this IDA does not show this message even when closed.

**Comment by StackOverflowExcept1on** [comment]
Thanks, now everything seems to be working even after an hour of running IDA

**Pull request merged**
